openapi: 3.0.3
info:
  description: Hal Demo API
  version: '1.0'
  title: Hal Demo
servers:
  - url: /api/v1

paths:
  /hal-demo/request:
    post:
      tags:
        - halDemo
      summary: notify about a hal-demo request
      operationId: requestHalDemo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HalDemo'
      responses:
        200:
          description: the hal-demo
          content:
            application/json:
              schema:
                description: the hal-demo id
                type: string
components:
  schemas:
    HalDemo:
      type: object
      properties:
        demoType:
          type: string
