spring:
  application:
    name: cash-workflow
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
    cash-a:
      change-log: classpath:liquibase/cash-a-master.yaml
      database-change-log-table: casha_changelog
      database-change-log-lock-table: casha_changeloglock
      contexts: cash-a   # see https://github.com/liquibase/liquibase/issues/4582
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5454/hal-bank
    password: hal-bank
    username: hal-bank

zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true

vanillabp:
  adapters:
    camunda8:
      resources-path: processes